<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['newslistcomments']['anonymous'] = 'Unbekannt';
$GLOBALS['TL_LANG']['newslistcomments']['submit'] = 'Abschicken';
$GLOBALS['TL_LANG']['newslistcomments']['comment_default'] = 'Schreibe einen Kommentar ...';
$GLOBALS['TL_LANG']['newslistcomments']['delete'] = 'L&ouml;schen';
$GLOBALS['TL_LANG']['newslistcomments']['news_default'] = "Was gibt's neues";
$GLOBALS['TL_LANG']['newslistcomments']['jumpTo'] = "Sieh Dir %s's Profil an.";
$GLOBALS['TL_LANG']['newslistcomments']['loadMore'] = 'Weitere Kommentare anzeigen';
