<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_module']['addNewslistComments']						= array('Kommentare hinzufügen', 'Fügt der Nachrichtenliste eine Kommentarfunktion für jeden Eintrag hinzu. <p style="color:gray">Das Template news_latest_comments muss gewählt sein.</p>');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_limit'] 				= array('Limit', 'Legt die Anzahl an Kommentaren fest, die direkt angezeigt werden. 0 für alle');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_maxLimit'] 				= array('Maximale Anzahl', 'Die Gesamtanzahl an Kommentaren, die angezeigt werden. 0 für alle');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_annonymus'] 			= array('Name Unbekannt', 'Dieser Name wird öffentlichen Usern gegeben.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_aliveTime'] 			= array('Löschen Timeout', 'Eingabe in Minuten. Zeitspanne in der das Löschen des Kommentars erlaubt ist.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_alwaysShowDelete'] 		= array('Löschen immer anzeigen', 'Die Lösch-Funktion für den Kommentar immer anzeigen.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_allowAll'] 				= array('Öffentliche Kommentare erlauben', 'Der User muss nicht angemeldet sein um Kommentare abzugeben.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_messagebox'] 			= array('Nachrichten-Box einfügen', 'Fügt eine Box zum Nachrichten erstellen oberhalb der Nachrichtenliste hinzu.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_dateFormat'] 			= array('Datums- und Zeitformat', 'Legen Sie das Format für die Zeitausgabe fest. Siehe php manual date()');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_timeFormat'] 			= array('Zeitformat', 'Zeitformat-String. Dient der Anzeige wie lange ein Kommentar bereits existiert. Siehe php manual date()');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_messagebox_template'] 	= array('Nachrichten-Box-Template', 'Wählen Sie das Template für die Nachrichten-Box');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_sortBy'] 				= array('Sortierung', 'Bitte wählen Sie die Art der Sortierung.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_sortBy']['DESC'] 		= 'Neuste oben';
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_sortBy']['ASC'] 		= 'Chronologisch';
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_avatar'] 				= array('Avatare hinzufügen', 'Fügt dem Kommentar einen Avatar hinzu. (Die Avatar Erweiterung muss dafür installiert sein)');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_nested'] 				= array('Verschachtelte Kommentare', 'Erlaubt es Kommentare zu kommentieren.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_template'] 				= array('Kommentar-Template', 'Wählen Sie das Ausgabe-Template für die Kommentar-Liste.');
$GLOBALS['TL_LANG']['tl_module']['newslist_comments_stoplevel'] 			= array('Kommentar-Tiefe', 'Geben Sie die maximale Verschachtelungstiefe für einen Kommentaren an.');


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_module']['newslistcomments_legend'] 				= 'Kommentar-Einstellungen';